const modules=[...document.querySelectorAll('.module')];
const panels=[...document.querySelectorAll('.panel')];
modules.forEach(b=>b.addEventListener('click',()=>{modules.forEach(x=>x.classList.remove('active'));panels.forEach(x=>x.classList.remove('active'));b.classList.add('active');document.getElementById(b.dataset.module).classList.add('active')}));

const form=document.getElementById('riskForm');
const steps=[...document.querySelectorAll('.step')];
const bars=[...document.querySelectorAll('.progress span')];
const next=document.getElementById('next');
const back=document.getElementById('back');
let current=0;
function data(){const f=new FormData(form);return {name:f.get('name')||'',industry:f.get('industry')||'',employees:f.get('employees')||'',locations:f.get('locations')||'',activities:f.getAll('activities'),data:f.get('data')||'',change:f.get('change')||'',concern:f.get('concern')||''}}
function show(i){current=i;steps.forEach((s,n)=>s.classList.toggle('active',n===i));bars.forEach((s,n)=>s.classList.toggle('active',n<=i));back.disabled=i===0;next.textContent=i===steps.length-1?'Generate draft snapshot':'Continue';if(i===3)review()}
function validate(){const required=[...steps[current].querySelectorAll('[required]')];return required.every(el=>el.checkValidity()||(el.reportValidity(),false))}
next.addEventListener('click',()=>{if(!validate())return;if(current<3)show(current+1);else generate()});back.addEventListener('click',()=>show(current-1));
function review(){const d=data();document.getElementById('reviewSummary').innerHTML=`<dl><dt>Organization</dt><dd>${escapeHtml(d.name)}</dd><dt>Profile</dt><dd>${escapeHtml(d.industry)}, ${escapeHtml(d.employees)} employees, ${escapeHtml(d.locations)}</dd><dt>Activities</dt><dd>${d.activities.length?d.activities.map(escapeHtml).join('; '):'None selected'}</dd><dt>Information</dt><dd>${escapeHtml(d.data)}</dd><dt>Recent change</dt><dd>${escapeHtml(d.change)}</dd></dl>`}
function rules(d){const areas=[],questions=[],docs=[];if(d.locations!=='One location'){areas.push('Operations across multiple locations');questions.push('How do responsibilities and activities differ by location?');docs.push('Current location and operations list')}if(d.activities.some(x=>x.includes('vehicles'))){areas.push('Vehicle use and transportation responsibilities');questions.push('Who owns, operates and maintains the vehicles?');docs.push('Vehicle and driver information')}if(d.activities.some(x=>x.includes('minors'))){areas.push('Programs involving minors or vulnerable populations');questions.push('What screening, supervision and incident procedures are documented?');docs.push('Program and safety procedures')}if(d.activities.some(x=>x.includes('volunteers'))){areas.push('Volunteer and contractor responsibilities');questions.push('How are volunteers or contractors selected, trained and supervised?');docs.push('Volunteer or contractor role descriptions')}if(d.activities.some(x=>x.includes('equipment'))){areas.push('Specialized property and equipment');questions.push('What property or equipment has changed since the last review?');docs.push('Equipment or property inventory')}if(d.activities.some(x=>x.includes('events'))){areas.push('Public events and fundraising activities');questions.push('Which events involve participants, vendors, facilities or transportation?');docs.push('Upcoming event schedule')}if(d.data.includes('sensitive')||d.data.includes('Financial')){areas.push('Sensitive information and technology practices');questions.push('What information is collected, who can access it and how is it protected?');docs.push('Data-handling and access summary')}if(d.change!=='No major change'){areas.push(d.change);questions.push('What changed operationally, and when did the change take effect?');docs.push('Documentation related to the recent change')}if(!areas.length){areas.push('Current operations and planned changes');questions.push('What changes are expected during the next 12 months?');docs.push('Current business overview')}return {areas:[...new Set(areas)],questions:[...new Set(questions)],docs:[...new Set(docs)]}}
function generate(){const d=data(),r=rules(d);form.classList.add('hidden');document.querySelector('.progress').classList.add('hidden');const report=document.getElementById('report');report.classList.remove('hidden');document.getElementById('reportContent').innerHTML=`<p><strong>${escapeHtml(d.name)}</strong> · ${escapeHtml(d.industry)} · ${escapeHtml(d.employees)} employees · ${escapeHtml(d.locations)}</p><div class="report-grid"><article class="report-card"><h3>Business changes and context</h3><ul><li>${escapeHtml(d.change)}</li><li>${escapeHtml(d.data)}</li>${d.concern?`<li>${escapeHtml(d.concern)}</li>`:''}</ul></article><article class="report-card"><h3>Discussion areas</h3><ul>${r.areas.map(x=>`<li>${escapeHtml(x)}</li>`).join('')}</ul></article><article class="report-card"><h3>Questions to confirm</h3><ul>${r.questions.map(x=>`<li>${escapeHtml(x)}</li>`).join('')}</ul></article><article class="report-card"><h3>Helpful preparation</h3><ul>${r.docs.map(x=>`<li>${escapeHtml(x)}</li>`).join('')}</ul></article></div>`;window.scrollTo({top:0,behavior:'smooth'})}
document.getElementById('printReport').addEventListener('click',()=>window.print());document.getElementById('startOver').addEventListener('click',()=>{form.reset();form.classList.remove('hidden');document.querySelector('.progress').classList.remove('hidden');document.getElementById('report').classList.add('hidden');show(0)});
document.getElementById('loadSample').addEventListener('click',()=>{form.elements.name.value='Front Range Youth Services';form.elements.industry.value='Nonprofit';form.elements.employees.value='20-49';form.elements.locations.value='Multiple locations in Colorado';[...form.querySelectorAll('[name=activities]')].forEach(x=>x.checked=['Works with minors or vulnerable populations','Relies on volunteers or contractors','Uses business or organization vehicles','Hosts public events or fundraisers'].includes(x.value));form.elements.data.value='Health, youth or other sensitive information';form.elements.change.value='New service or program';form.elements.concern.value='We are launching a youth transportation program at a second location.';show(3)});
function escapeHtml(v){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}

const triggerData=[
 {name:'Front Range Youth Services',event:'New youth transportation program',score:10,source:'Organization news release · Sep 18, 2026',why:'Vehicles, volunteers and participant responsibilities may have changed.',questions:['When will transportation begin?','Who owns, operates and maintains the vehicles?','How are drivers and volunteers selected and supervised?'],outreach:'Congratulations on the new transportation program. I would be glad to help you think through the operational changes and questions worth reviewing as the program launches.'},
 {name:'Precision Optics Co.',event:'Second production facility announced',score:9,source:'Longmont business announcement · Sep 16, 2026',why:'Property, specialized equipment, workforce and location responsibilities may have changed.',questions:['When does the new facility become operational?','What equipment and processes will move or be added?','Will employee roles or transportation change?'],outreach:'I saw the announcement about your second production facility. Expansion often creates operational changes worth reviewing early. I would be happy to compare notes as the new location comes online.'},
 {name:'Community Arts Fund',event:'Annual fundraising event scheduled',score:5,source:'Public event calendar · Sep 14, 2026',why:'The event may involve vendors, volunteers, facilities and public participation.',questions:['Is this event materially different from prior years?','Are new vendors, venues or activities involved?'],outreach:'I noticed your upcoming fundraising event and would be glad to help review what has changed from prior years.'}
];
function animateSteps(container,done){const xs=[...container.querySelectorAll('.flow-step')];xs.forEach(x=>x.classList.remove('active','done'));let i=0;const tick=()=>{if(i>0){xs[i-1].classList.remove('active');xs[i-1].classList.add('done')}if(i<xs.length){xs[i].classList.add('active');i++;setTimeout(tick,260)}else done()};tick()}
document.getElementById('runTriggerScan').addEventListener('click',()=>{const btn=document.getElementById('runTriggerScan');btn.disabled=true;btn.textContent='Scanning…';animateSteps(document.getElementById('triggerSteps'),()=>{document.getElementById('triggerEmpty').classList.add('hidden');document.getElementById('triggerResults').classList.remove('hidden');renderTriggers();btn.disabled=false;btn.textContent='Run again'})});
function renderTriggers(){const list=document.getElementById('triggerList');list.innerHTML=triggerData.map((x,i)=>`<button class="record" data-trigger="${i}"><span class="score">${x.score}/10</span><b>${escapeHtml(x.name)}</b><small>${escapeHtml(x.event)}</small></button>`).join('');list.querySelectorAll('.record').forEach(b=>b.addEventListener('click',()=>showTrigger(+b.dataset.trigger,b)));list.querySelector('.record').click()}
function showTrigger(i,button){document.querySelectorAll('.record').forEach(x=>x.classList.remove('active'));button.classList.add('active');const x=triggerData[i],d=document.getElementById('triggerDetail');d.innerHTML=`<h2>${escapeHtml(x.name)}</h2><p><b>${escapeHtml(x.event)}</b></p><div class="source-box"><b>Evidence source</b><br>${escapeHtml(x.source)}</div><div class="detail-grid"><div><b>Why it may matter</b>${escapeHtml(x.why)}</div><div><b>Questions to consider</b><ul>${x.questions.map(q=>`<li>${escapeHtml(q)}</li>`).join('')}</ul></div></div><div class="source-box"><b>Draft outreach for Kirk to edit</b><br>${escapeHtml(x.outreach)}</div><div class="decision-bar"><button class="primary" data-action="approve">Approve for outreach</button><button class="ghost" data-action="later">Review later</button><button class="ghost" data-action="dismiss">Dismiss</button></div><p class="decision-message hidden"></p>`;d.querySelectorAll('[data-action]').forEach(b=>b.addEventListener('click',()=>{const m=d.querySelector('.decision-message');m.classList.remove('hidden');m.textContent=b.dataset.action==='approve'?'Approved for Kirk’s personal review and outreach. Nothing was sent automatically.':b.dataset.action==='later'?'Saved for later review.':'Dismissed from this week’s queue.'}))}

const clients={
 'front-range':{baselineTitle:'One Colorado location',baselineText:'Youth services, 18 employees, volunteers used, no transportation program recorded.',changeTitle:'Second location and transportation announced',changeText:'The organization website describes passenger transportation for a new program at a second Colorado location.',questions:['Confirm whether the second location is operating.','Ask when transportation begins and who operates the vehicles.','Confirm employee and volunteer responsibilities.','Request updated program and transportation procedures.']},
 'precision':{baselineTitle:'Single manufacturing facility',baselineText:'Precision components, 32 employees and specialized production equipment at one Longmont facility.',changeTitle:'Second production facility announced',changeText:'A public announcement describes a second facility, additional equipment and planned hiring.',questions:['Confirm the operational date for the second facility.','Identify equipment being added or relocated.','Confirm expected workforce and responsibility changes.','Request an updated property and equipment list.']}
};
document.getElementById('runClientCheck').addEventListener('click',()=>{const btn=document.getElementById('runClientCheck');btn.disabled=true;btn.textContent='Comparing…';animateSteps(document.getElementById('clientSteps'),()=>{const x=clients[document.getElementById('clientSelect').value];document.getElementById('baselineTitle').textContent=x.baselineTitle;document.getElementById('baselineText').textContent=x.baselineText;document.getElementById('changeTitle').textContent=x.changeTitle;document.getElementById('changeText').textContent=x.changeText;document.getElementById('clientQuestions').innerHTML=x.questions.map(q=>`<li>${escapeHtml(q)}</li>`).join('');document.getElementById('clientEmpty').classList.add('hidden');document.getElementById('clientResults').classList.remove('hidden');document.getElementById('clientDecision').classList.add('hidden');btn.disabled=false;btn.textContent='Check again'})});
document.getElementById('markConfirmed').addEventListener('click',()=>clientDecision('Change marked confirmed for Kirk’s review. The official client record was not changed automatically.'));
document.getElementById('markNotRelevant').addEventListener('click',()=>clientDecision('Signal marked not relevant and retained in the review history.'));
document.getElementById('printBrief').addEventListener('click',()=>window.print());
function clientDecision(text){const m=document.getElementById('clientDecision');m.textContent=text;m.classList.remove('hidden')}
show(0);
